### ISSUE TITLE
Excessive heat on ESP32 AMS1117 regulator due to high rectified 9v.

### ISSUE THREAD

**Issue by Ming-Kerr** [WiC64-Team/wic64-hardware#1]
Hello.
This circuit actually destroyed a few of the cheap clone ESP's I tried with it, and the "official" ESP32 AMS1117 still runs unnervingly hot, right at the edge of voltage input specs.
I fixed this entirely by removing diode D3 and wiring a 7805 regulator's IN and GND pins direct to the bridge rectifier +/-, then the output pin to VIN just past where D3 was with a short jumper wire. Turning the 7805 upside down means it can be kept relatively neat and flush.
No concerns now. Neither gets particularly warm.
Even the cheap Chinese ESP32 clone's should survive with this change.

Cheers now.

**Comment by GMP64** [comment]
Hello,
unfortunately, I have to disagree with you. Normally, the circuit does not destroy anything. According to the data sheet, the voltage regulator is designed for a maximum temperature of up to 125°C and can withstand a maximum input voltage of 15V. Yes, it gets hot. Measured at full load with a thermal imaging camera, we were at 80 degrees.
As you write that several ESPs have been destroyed, please check your power supply unit. There is probably a fundamental problem on the 9Volt~ line. We have not yet received any negative feedback from others to this extent.
Best wishes.

**Comment by Ming-Kerr** [comment]
9v line on the PSU is fine, measuring just under 10v with a MM. The regulator was getting hotter than 80C.
The cheap Chinese ones that died have different components around the AMS1117, e.g. a diode swapped with a zero ohm resistor and I suspect the capacitors were specced with too low voltage ratings, expecting 5v.
Anyway, I'm happy with my particular solution that is keeping everything cool.

**Comment by GMP64** [comment]
Yes, I agree with you. We can't know exactly where the modules come from and whether the manufacturer adheres exactly to the circuit specifications. That's a big problem. And this zero-ohm resistor has already caused us a lot of trouble.

**Comment by Ming-Kerr** [comment]
I will close the issue now, as that aspect is more related to the odd off kilter batch of ESP32's.
Just thought I'd point out one workaround if anyone else comes across the same sort of thing with very hot AMS as well.

Cheers now.
